### ISSUE TITLE
react-tap-event-plugin doesn't work as expected

### ISSUE THREAD

**Issue by pimkle** [callemall/material-ui-browserify-gulp-example#2]
https://github.com/callemall/material-ui/issues/5396

I got similar error, and solved it this way:

You need to use the latest version of react-tap-event-plugin which relies on the correct internal library from react-dom instead of react

"react-tap-event-plugin": "^2.0.1"

**Comment by oliviertassinari** [comment]
@pimkle Thanks for letting us know.
